## PostgreSQL
spring:
  liquibase:
    change-log: classpath:db/master.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/reactiveDb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
---

server:
  port: 8085

demo:
  username: zaur
  password: zaur123

